#!/bin/bash
set -e -o pipefail


## [2019-11-19]
## 
##   This script should be in the folder with VirtualBox virtual machines.
##   
##   After having run it, please modify the generated .vbox file:
##     Change
##       <Logo fadeIn="true" fadeOut="true" displayTime="0" imagePath="Isabeau-1-cropped.bmp"/>
##     to
##       <Logo fadeIn="true" fadeOut="true" displayTime="0" imagePath="G:/VM_G/191119-015328_Deborah/Isabeau-1-cropped.bmp"/>
##     (of course, replacing with the full pathname of where the image resides).
##     This enables the boot logo image.


function Create ()
{
	which VBoxManage
	
	local tNow="$(cygwin-date +"%y%m%d-%H%M%S")"
	#local tUse="190925-141300"
	local tUse="${tNow}"
	echo "tNow ${tNow}, tUse {$tUse}..."
	
	local sName="${tUse}_Deborah"
	
	
	
	if ((1)); then
		if [ -d "${sName}/" ]; then
			echo "Unregistering \"${sName}\..."
			set +e
			VBoxManage unregistervm "${sName}"
			mv "${sName}/"          "${sName}_${tNow}"
			set -e
			echo
		fi
		
		if true; then
			echo "Creating machine \"${sName}\"..."
			if   [ -d "${sName}/" ]; then echo "\"${sName}\" is already a folder !"; exit 1; fi
			VBoxManage createvm --name "${sName}" --ostype "Debian_64" --register
			if ! [ -d "${sName}/" ]; then echo "\"${sName}\" is not a folder !"    ; exit 1; fi
			echo
		fi
	fi
	
	
	
	if ((0)); then
		echo "Showing..."
		VBoxManage showvminfo "${sName}"
		echo
	fi
	
	
	
	if ((1)); then
		echo "Modifying..."
		VBoxManage modifyvm "${sName}" \
			--memory                   2048          \
			--vram                       32          \
			--ioapic                   on            \
			--rtcuseutc                on            \
			--cpus                        2          \
			--accelerate2dvideo        off           \
			--accelerate3d             on            \
			\
			--clipboard                bidirectional \
			--draganddrop              bidirectional \
			\
			--bioslogoimagepath        "Isabeau-1-cropped.bmp" \
			--boot1                    "none"        \
			--boot2                    "dvd"         \
			--boot3                    "disk"        \
			--boot4                    "none"        \
		
		VBoxManage storagectl "${sName}" --name "IDE"  --add "ide"
		VBoxManage storagectl "${sName}" --name "SATA" --add "sata"
		
		echo
	fi
	
	
	
	if ((0)); then
		echo "Showing..."
		VBoxManage showvminfo "${sName}"
		echo
	fi
	
	
	
	echo
	
	if ((1)); then
		echo "Creating disks..."
		
		#VBoxManage storageattach "${sName}" --storagectl "IDE" --port "0" --device "0" --type "dvddrive" --medium "none"
		
		#sVariant="Split2G"
		sVariant="Standard"
		
		local asDisks=()
		{
			asDisks+=("Root;32768")
			asDisks+=("Swap;2048")
			asDisks+=("Home;4096")
			asDisks+=("DevKits;32768")
		}
		
		local iDisk=0
		local sDisk
		for sDisk in "${asDisks[@]}"; do
			#echo "\"${sDisk}\""
			local asSubDisks=()
			{
				IFS=";" read -r -a asSubDisks <<< "${sDisk}"
				
				#local sSubDisk
				#for sSubDisk in "${asSubDisks[@]}"; do
				#	echo "    \"${sSubDisk}\""
				#done
				
				local sDiskName="${asSubDisks[0]}"
				local sDiskSize="${asSubDisks[1]}"
				printf "    %-16s %'9u\n" "${sDiskName}" "${sDiskSize}"
				
				set +e
				VBoxManage closemedium  disk                                                 "${sName}/${sDiskName}.vmdk" --delete >/dev/null 2>&1
				set -e
				VBoxManage createmedium disk --format "VMDK" --variant "Standard" --filename "${sName}/${sDiskName}.vmdk" --size "${sDiskSize}"
				VBoxManage storageattach "${sName}" --storagectl "SATA" --port "${iDisk}" --type "hdd" --medium "${sName}/${sDiskName}.vmdk" --mtype "normal"
			}
			
			((++iDisk))
		done
		
		echo
	fi
	
	
	
	echo "Hello, World !"
}

Create
if [ $? -ne 0 ]; then echo "Error $? !"; fi
